use crate::batches::Batch;
use crate::fifo::StockLedgerEntry;
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};

/// Discrepancy detected between recorded batch master remaining quantity and the physical stock ledger.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BatchDiscrepancy {
    /// Batch ID.
    pub batch_id: String,
    /// Item code.
    pub item_code: String,
    /// Recorded quantity on Batch master document.
    pub recorded_batch_qty: Decimal,
    /// Actual cumulative quantity derived from all Stock Ledger Entries.
    pub ledger_qty: Decimal,
    /// Difference: `ledger_qty - recorded_batch_qty`.
    pub difference: Decimal,
}

/// Audit summary generated by the batch quantity recalculator.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BatchAuditReport {
    /// Total batches examined.
    pub batches_examined: usize,
    /// List of batches with non-zero discrepancies.
    pub discrepancies: Vec<BatchDiscrepancy>,
}

/// Batch Quantity Recalculator engine for reconciling physical stock ledger entries with batch balances.
pub struct BatchRecalculator;

impl BatchRecalculator {
    /// Evaluates stock ledger entries associated with batches and calculates actual balances.
    pub fn audit_batches(
        batches: &[Batch],
        stock_entries: &[StockLedgerEntry],
    ) -> BatchAuditReport {
        let mut discrepancies = Vec::new();

        for batch in batches {
            let actual_ledger_qty: Decimal = stock_entries
                .iter()
                .filter(|sle| {
                    sle.item_code == batch.item_code && sle.voucher_no.contains(&batch.batch_id)
                })
                .map(|sle| sle.actual_qty)
                .sum();

            if actual_ledger_qty != batch.remaining_qty {
                discrepancies.push(BatchDiscrepancy {
                    batch_id: batch.batch_id.clone(),
                    item_code: batch.item_code.clone(),
                    recorded_batch_qty: batch.remaining_qty,
                    ledger_qty: actual_ledger_qty,
                    difference: actual_ledger_qty - batch.remaining_qty,
                });
            }
        }

        BatchAuditReport {
            batches_examined: batches.len(),
            discrepancies,
        }
    }

    /// Reconciles a batch by returning an updated batch struct with corrected remaining quantity.
    pub fn reconcile_batch(mut batch: Batch, actual_qty: Decimal) -> Batch {
        batch.remaining_qty = actual_qty;
        batch
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::NaiveDate;
    use rust_decimal_macros::dec;

    #[test]
    fn test_batch_recalculation_and_reconcile() {
        let batch = Batch {
            batch_id: "BATCH-2026-X".into(),
            item_code: "CHEMICAL-A".into(),
            mfg_date: NaiveDate::from_ymd_opt(2026, 1, 1).unwrap(),
            expiry_date: None,
            remaining_qty: dec!(100.0), // Recorded as 100
        };

        let date = NaiveDate::from_ymd_opt(2026, 2, 1).unwrap();
        let entries = vec![
            StockLedgerEntry {
                name: "SLE-01".into(),
                item_code: "CHEMICAL-A".into(),
                warehouse: "Main Stores".into(),
                actual_qty: dec!(150.0), // Received 150
                incoming_rate: dec!(10.0),
                valuation_rate: dec!(10.0),
                stock_value_difference: dec!(1500.0),
                posting_date: date,
                voucher_type: "Purchase Receipt".into(),
                voucher_no: "PR-BATCH-2026-X".into(),
            },
            StockLedgerEntry {
                name: "SLE-02".into(),
                item_code: "CHEMICAL-A".into(),
                warehouse: "Main Stores".into(),
                actual_qty: dec!(-70.0), // Dispatched 70 -> Net remaining is 80
                incoming_rate: dec!(10.0),
                valuation_rate: dec!(10.0),
                stock_value_difference: dec!(-700.0),
                posting_date: date,
                voucher_type: "Delivery Note".into(),
                voucher_no: "DN-BATCH-2026-X".into(),
            },
        ];

        let report = BatchRecalculator::audit_batches(std::slice::from_ref(&batch), &entries);
        assert_eq!(report.discrepancies.len(), 1);
        assert_eq!(report.discrepancies[0].recorded_batch_qty, dec!(100.0));
        assert_eq!(report.discrepancies[0].ledger_qty, dec!(80.0));
        assert_eq!(report.discrepancies[0].difference, dec!(-20.0));

        let reconciled = BatchRecalculator::reconcile_batch(batch, dec!(80.0));
        assert_eq!(reconciled.remaining_qty, dec!(80.0));
    }
}
