apiVersion: v1
kind: ConfigMap
metadata:
  name: rustnext-config
  namespace: rustnext
data:
  RUST_LOG: "info"
  MICRO_MODE: "false"
  ACME_EMAIL: "admin@enterprise.local"
  DATABASE_PATH: "surrealkv:///data/rustnext.db"
