apiVersion: v1
kind: Secret
metadata:
  name: rustnext-secrets
  namespace: rustnext
type: Opaque
stringData:
  RUSTNEXT_MASTER_TOKEN_SECRET: "rustnext_enterprise_paseto_master_secret_key_2026_offline_first_32bytes_min"
  RUSTNEXT_JWT_SECRET: "rustnext_enterprise_jwt_secret_key_2026_offline_first"
  STRIPE_WEBHOOK_SECRET: "whsec_enterprise_production_webhook_secret_key"
  ADMIN_INITIAL_PASSWORD: "admin"
