// RustNext Enterprise Auto-Generated TypeScript SDK
// Generated by rbench sdk generate

export interface SessionClaims {
  sub: string;
  tenant_id: string;
  roles: string[];
  exp: number;
}

export interface LoginResponse {
  message: string;
  home_page: string;
  full_name: string;
  user_id: string;
  token: string;
  roles: string[];
  expires_at: number;
}

export interface DocumentResponse<T = Record<string, any>> {
  doc?: T;
  data?: T[];
  message?: string;
  error?: string;
}

export interface WebhookSubscription {
  id: string;
  event: string;
  target_url: string;
  secret: string;
  is_active: boolean;
  created_at: string;
}
