[package]
name = "frappe-framework"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
frappe-meta = { workspace = true }
frappe-storage = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
rust_decimal = { workspace = true }
chrono = { workspace = true }
compact_str = { workspace = true }
rhai = { workspace = true }
tracing = { workspace = true }
wasmtime = { workspace = true }
sha2 = { workspace = true }
hmac = { workspace = true }
hex = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
rust_decimal_macros = { workspace = true }

