[package]
name = "erp-software"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
frappe-meta = { workspace = true }
frappe-framework = { workspace = true }
erp-accounting = { workspace = true }
erp-ppm = { workspace = true }
erp-support = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
