[package]
name = "frappe-net"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
frappe-meta = { workspace = true }
frappe-storage = { workspace = true }
frappe-framework = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
regex = { workspace = true }
actix-web = { workspace = true }
actix-ws = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
surrealdb = { workspace = true }
clap = { workspace = true }
erp-cms = { workspace = true }
compact_str = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
desk-app = { workspace = true }
desk-components = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
argon2 = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }


[dev-dependencies]
frappe-meta = { workspace = true }
frappe-storage = { workspace = true }
frappe-framework = { workspace = true }
erp-accounting = { workspace = true }
erp-inventory = { workspace = true }
erp-manufacturing = { workspace = true }
erp-trade = { workspace = true }
erp-ppm = { workspace = true }
erp-asset = { workspace = true }
erp-wms = { workspace = true }
erp-cms = { workspace = true }
desk-components = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
compact_str = { workspace = true }
