[package]
name = "erp-cms"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
frappe-meta = { workspace = true }
frappe-framework = { workspace = true }
frappe-storage = { workspace = true }
erp-accounting = { workspace = true }
erp-trade = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
compact_str = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
