[package]
name = "desk-app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "desk_app"
path = "src/lib.rs"

[[bin]]
name = "desk-app"
path = "src/main.rs"

[dependencies]
frappe-meta = { workspace = true }
desk-components = { workspace = true }
frappe-storage = { workspace = true }
chrono = { workspace = true }
compact_str = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
