use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};

/// Planned order type generated by MRP.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OrderType {
    /// In-house manufacturing order.
    WorkOrder,
    /// External procurement order.
    PurchaseOrder,
}

/// Generated MRP replenishment requirement plan.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PlannedOrder {
    /// Target item code.
    pub item_code: String,
    /// Net required replenishment quantity.
    pub qty: Decimal,
    /// Recommended order type.
    pub order_type: OrderType,
    /// Lead time in days.
    pub lead_time_days: u32,
}

/// Material Requirements Planning (MRP) Engine (Milestone 3.3).
pub struct MrpEngine;

impl MrpEngine {
    /// Calculates net production and procurement requirements:
    /// $\text{Net Required} = \text{Gross Demand} - \text{Current Stock} - \text{Open PO} + \text{Safety Stock}$
    #[must_use]
    pub fn calculate_net_requirement(
        gross_demand: Decimal,
        current_stock: Decimal,
        open_purchase_orders: Decimal,
        safety_stock: Decimal,
    ) -> Decimal {
        let net = gross_demand - current_stock - open_purchase_orders + safety_stock;
        net.max(Decimal::ZERO)
    }

    /// Generates a planned replenishment order.
    #[must_use]
    pub fn plan_order(
        item_code: &str,
        gross_demand: Decimal,
        current_stock: Decimal,
        open_po: Decimal,
        safety_stock: Decimal,
        is_manufactured: bool,
        lead_time_days: u32,
    ) -> Option<PlannedOrder> {
        let net =
            Self::calculate_net_requirement(gross_demand, current_stock, open_po, safety_stock);
        if net > Decimal::ZERO {
            Some(PlannedOrder {
                item_code: item_code.to_string(),
                qty: net,
                order_type: if is_manufactured {
                    OrderType::WorkOrder
                } else {
                    OrderType::PurchaseOrder
                },
                lead_time_days,
            })
        } else {
            None
        }
    }
}

/// Scheduled operational time window on a workstation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ScheduledSlot {
    /// Operation or job identifier.
    pub job_id: String,
    /// Start timestamp (e.g. minutes from epoch/shift start).
    pub start_time: u64,
    /// End timestamp.
    pub end_time: u64,
}

/// Workstation Interval Scheduler with Conflict-Free Forward Sliding (Milestone 3.4).
#[derive(Debug, Default, Clone)]
pub struct WorkstationScheduler {
    /// Workstation ID -> Ordered list of booked non-overlapping slots.
    bookings: std::collections::HashMap<String, Vec<ScheduledSlot>>,
}

impl WorkstationScheduler {
    /// Creates a new scheduler instance.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Schedules an operation interval, automatically sliding forward if a collision occurs.
    /// Returns the assigned `ScheduledSlot`.
    pub fn schedule_operation(
        &mut self,
        workstation: &str,
        job_id: String,
        mut desired_start: u64,
        duration: u64,
    ) -> ScheduledSlot {
        let slots = self.bookings.entry(workstation.to_string()).or_default();

        // Sort existing slots by start time
        slots.sort_by_key(|s| s.start_time);

        // Slide forward until we find an available window
        for booked in slots.iter() {
            let desired_end = desired_start + duration;
            // Collision condition: max(start1, start2) < min(end1, end2)
            if desired_start.max(booked.start_time) < desired_end.min(booked.end_time) {
                // Collides: slide desired_start forward to end of booked slot
                desired_start = booked.end_time;
            }
        }

        let assigned = ScheduledSlot {
            job_id,
            start_time: desired_start,
            end_time: desired_start + duration,
        };

        slots.push(assigned.clone());
        assigned
    }
}
